# languages: German (deu), English (eng), French (fr), custom Messages (custom), SÃ¤chsisch (sachs)
Language: deu

# reasons why player report anyone
# (advertising, hacking)
Reasons:
- Hacking
- Spamm
- Werbung

# choose sqlite or mysql
provider: sqlite
mysql:
  host: "127.0.0.1"
  port: 3306
  username: ""
  password: ""
  database: ""
  table: ""

# when you want, that the reports will send to a discord server, set them to true
SendToDiscord: false
# name of Discord webhook
WebhookName: "AdvancedReport"
# url of Discord webhook
Webhook: ""